# Generated by Django 5.1.2 on 2024-11-01 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0002_bindata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BinData',
        ),
    ]
