# Generated by Django 5.1.2 on 2024-11-26 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0004_bin_is_full_alter_bin_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bin',
            options={'ordering': ['bin_id']},
        ),
    ]
