# Generated by Django 5.1.2 on 2024-12-04 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0006_datacollection_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datacollection',
            options={'permissions': [('can_view_bin_data', 'Peut voir les données des poubelles'), ('can_edit_bin_data', 'Peut modifier les données des poubelles')]},
        ),
    ]
