# Generated by Django 5.1.2 on 2024-10-14 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_id', models.CharField(max_length=10, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('capacity', models.FloatField()),
                ('type', models.CharField(choices=[('Plastique', 'Plastique'), ('Papier', 'Papier'), ('Verre', 'Verre'), ('Métal', 'Métal'), ('Déchets organiques', 'Déchets organiques'), ('Autre', 'Autre')], default='Autre', max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_emptied_at', models.DateTimeField(blank=True, null=True)),
                ('users', models.ManyToManyField(blank=True, related_name='bins_managed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.FloatField()),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('signal_strength', models.FloatField()),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_collections', to='garbage.bin')),
            ],
        ),
    ]
